<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Models\Curriculum;
use App\Http\Resources\Api\V1\CurriculumResource;
use Illuminate\Http\Request;

class CurriculumController extends Controller
{
    public function index(Request $request)
    {
        $curriculums = $request->user()->curriculums()->latest()->get();
        return CurriculumResource::collection($curriculums);
    }

    public function show(Request $request, Curriculum $curriculum)
    {
        if ($curriculum->user_id !== $request->user()->id) {
            return response()->json(['message' => 'Unauthorized'], 403);
        }

        $curriculum->load(['milestones' => function($q) {
            $q->orderBy('order_index', 'asc');
        }]);

        return new CurriculumResource($curriculum);
    }

    public function generate(Request $request, \App\Services\AiCurriculumService $aiService)
    {
        $request->validate([
            'topic' => 'required|string|max:255'
        ]);

        $generatedData = $aiService->generateCurriculum($request->topic);

        if (!$generatedData) {
            return response()->json(['message' => 'Gagal menghasilkan kurikulum dari AI. Silakan coba lagi.'], 500);
        }

        try {
            \Illuminate\Support\Facades\DB::beginTransaction();

            $curriculum = $request->user()->curriculums()->create([
                'topic' => $generatedData['topic'] ?? $request->topic,
                'description' => $generatedData['description'] ?? 'Generated by AI',
                'total_progress' => 0,
                'is_completed' => false,
            ]);

            $milestones = $generatedData['milestones'] ?? [];
            foreach ($milestones as $index => $milestoneData) {
                $curriculum->milestones()->create([
                    'title' => $milestoneData['title'],
                    'order_index' => $index + 1,
                    'is_completed' => false,
                ]);
            }

            \Illuminate\Support\Facades\DB::commit();

            $curriculum->load(['milestones' => function($q) {
                $q->orderBy('order_index', 'asc');
            }]);

            return response()->json([
                'message' => 'Kurikulum berhasil dibuat',
                'data' => new CurriculumResource($curriculum)
            ], 201);

        } catch (\Exception $e) {
            \Illuminate\Support\Facades\DB::rollBack();
            return response()->json(['message' => 'Gagal menyimpan kurikulum: ' . $e->getMessage()], 500);
        }
    }
}
